name: Swiftify
options:
  bundleIdPrefix: com.moritzwendt
  deploymentTarget:
    iOS: "26.1"
settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: YZ78A69UF8
    CODE_SIGN_STYLE: Automatic
targets:
  Swiftify:
    type: application
    platform: iOS
    sources:
      - Sources
      - path: Icon/AppIcon.icon
        type: file
        buildPhase: resources
    postBuildScripts:
      - name: Generate Build Number
        script: '"$SRCROOT/Scripts/generate_build_number.sh"'
        basedOnDependencyAnalysis: false
        inputFiles:
          - $(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moritzwendt.swiftify
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Swiftify
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
